config/routes.rb
CommitsIO::Application.routes.draw do
  # omniauth-github
  get '/auth/github/callback' => 'web/social_network#authorization'
  get '/auth/github/failure' => 'web/social_network#failure'

  scope :module => :web do
    root :to => 'welcome#show'
    resource :session, only: [:new, :create, :destroy]

    resource :social_network, :only => [] do 
      get :authorization, :on => :member
    end

    resource :hook, only: :create

    get :profile, controller: :users, action: :profile
    get :dashboard, controller: :users, action: :dashboard

    scope :module => :users do
      namespace :settings do
        get :repositories
        get :personal
        post :activate_repository
        put :update_personal
      end
    end

    resources :profiles, only: [:show], controller: :users
    resources :users, only: [], constraints: { owner: /[a-zA-Z.\/0-9_\-]+/ }, path: "/" do
      resources :repositories, only: [:show], constraints: { repository: /[a-zA-Z.\/0-9_\-]+/ }, path: "/" do
        scope module: :repositories do
          resources :commits, only: [:index, :show]
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :name, :login, :image, :password, :password_confirmation, :birthday

  validates :email, uniqueness: { case_sensitive: false }
  validates :login, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, allow_blank: true
  validates :name, length: { maximum: 255 }

  has_many :auth_tokens
  has_many :authorizations
  has_many :user_badges, :dependent => :destroy
  has_many :repositories, dependent: :nullify
  has_one :committer, foreign_key: :email, primary_key: :email
  has_many :commit_metrics

  def guest?
    false
  end

  def build_auth_token
    token = SecureHelper.generate_token
    expired_at = Time.current + configus.token.lifetime
    auth_tokens.build :authentication_token => token, :expired_at => expired_at
  end

  class << self
    def birthday_year_min
      Date.today.year - 90
    end

    def birthday_year_max
      Date.today.year - 10
    end
  end
end

app/models/user/auth_token.rb
class User::AuthToken < ActiveRecord::Base

  belongs_to :user

  attr_accessible :authentication_token, :expired_at 

  validates :user, :presence => true
  validates :authentication_token, :presence => true, :uniqueness => true
  validates :expired_at, :presence => true

  def to_s
    authentication_token
  end

  def expired?
    expired_at < Time.current
  end
end

app/controllers/web/users/application_controller.rb
class Web::Users::ApplicationController < Web::ProtectedApplicationController

  def resource_user
    current_user
  end
end

app/controllers/web/users/settings_controller.rb
class Web::Users::SettingsController < Web::Users::ApplicationController
  def repositories
    github = Github.new oauth_token: get_auth_token
    external_repositories = RepositoryBuilder.build_list(github.repos.list(user: resource_user.login), :github)
    internal_repositories = resource_user.repositories
    @repositories = external_repositories.map {|er| internal_repositories.find_by_name(er.name) || er }
  end

  def activate_repository
    if resource_user.email.blank?
      flash_error(now: false)
      return redirect_to action: :personal
    end

    github = Github.new oauth_token: get_auth_token
    repository = RepositoryBuilder.build(github.repos.get(resource_user.login, params[:repository]), :github)

    # TODO [AK] think about this place
    committer = resource_user.committer
    repository.ownerable = committer if committer

    repository.user = resource_user
    RepositoryCreator.create(repository)

    redirect_to action: :repositories
  end

  def personal
    @user = resource_user.becomes UserEditType
  end

  def update_personal
    @user = resource_user.becomes UserEditType
    @user.update_attributes(params[:user])
    render action: :personal
  end
end

app/controllers/web/users_controller.rb
class Web::UsersController < Web::ApplicationController

  def dashboard
    authenticate!

    @commits = Commit.scoped
  end

  def profile
    @user = User.find_by_login!(params[:login]) if params[:login]
    @user ||= current_user if signed_in?
    raise ActiveRecord::RecordNotFound unless @user.present?
  end
end

app/views/web/users/settings/personal.html.haml
.row-fluid
  .span3
    %ul.nav.nav-list
      %li
        =link_to t(".Settings"), settings_personal_path
      %li
        =link_to t(".Repositories"), settings_repositories_path
  .span9
    = simple_form_for @user, html: {class: 'form-horizontal'}, url: settings_update_personal_path do |f|
      = f.error_notification
      = f.input :name
      = f.input :email
      = f.input :birthday, as: :string
      .control-group
        .controls
          = f.button :submit, class: 'btn btn-success'

app/views/web/users/settings/repositories.html.haml
.row-fluid
  .span3
    %ul.nav.nav-list
      %li
        =link_to t(".Settings"), settings_personal_path
      %li
        =link_to t(".Repositories"), settings_repositories_path
  .span9
    %h2
      = t(".Repositories")
      %span.pull-right
        %i.icon-spinner.icon-spin
        %span.btn.btn-success
          = t(".sync")

    %br
    %table.table
      %tbody
      - @repositories.each do |r|
        %tr
          %td= r.name
          %td.right
            - unless r.id?
              = link_to t('.activate'), settings_activate_repository_path(repository: r.name), method: :post
            - else
              = t('.activated')