config/routes.rb
CommitsIO::Application.routes.draw do
  # omniauth-github
  get '/auth/github/callback' => 'web/social_network#authorization'
  get '/auth/github/failure' => 'web/social_network#failure'

  scope :module => :web do
    root :to => 'welcome#show'
    resource :session, only: [:new, :create, :destroy]

    resource :social_network, :only => [] do 
      get :authorization, :on => :member
    end

    resource :hook, only: :create

    get :profile, controller: :users, action: :profile
    get :dashboard, controller: :users, action: :dashboard

    scope :module => :users do
      namespace :settings do
        get :repositories
        get :personal
        post :activate_repository
        put :update_personal
      end
    end

    resources :profiles, only: [:show], controller: :users
    resources :users, only: [], constraints: { owner: /[a-zA-Z.\/0-9_\-]+/ }, path: "/" do
      resources :repositories, only: [:show], constraints: { repository: /[a-zA-Z.\/0-9_\-]+/ }, path: "/" do
        scope module: :repositories do
          resources :commits, only: [:index, :show]
        end
      end
    end
  end
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base

  belongs_to :user

  attr_accessible :provider, :uid

  validates :provider, :presence => true
  validates :uid, :presence => true

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  attr_accessible :description, :image, :name

  has_many :user_badges, :dependent => :destroy

  validates :name, presence: true, length: { maximum: 255 }
end

app/models/commit.rb
class Commit < ActiveRecord::Base
  attr_accessible :committer_id, :diff, :parent_sha, :repository_id, :sha, :message, :committed_at, :percent

  has_many :commit_metrics, :dependent => :destroy

  belongs_to :committer
  belongs_to :repository

  validates :committer, presence: true
  validates :repository, presence: true
  validates :sha, presence: true, length: { maximum: 255 }
  validates :parent_sha, length: { maximum: 255 }
  validates :message, presence: true
  validates :committed_at, presence: true

  scope :bottom, -> { order(:percent, :committed_at).limit(10) }
  scope :top, -> { where('percent > 0').order("percent DESC, committed_at DESC").limit(10) }
end

app/models/commit_metric.rb
class CommitMetric < ActiveRecord::Base
  attr_accessible :commit_id, :data, :metric_id, :user_id, :rate, :metric_coumt
  belongs_to :metric
  belongs_to :commit
  belongs_to :user

  validates :commit, presence: true
  validates :data, presence: true
  validates :metric, presence: true

  def presenter
    @presenter ||= CommitsService.get_presenter(self)
  end
end

app/models/committer.rb
class Committer < ActiveRecord::Base
  attr_accessible :email, :name, :organization_id, :user_id

  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :name, presence: true, length: { maximum: 255 }

  belongs_to :organization
  has_one :user, foreign_key: :email, primary_key: :email

  has_many :repositories, :as => :ownerable
  has_many :commits, :dependent => :destroy

  def to_s
    name
  end
end

app/models/guest.rb
class Guest
  def guest?
    true
  end

  def admin?
    false
  end
end

app/models/metric.rb
class Metric < ActiveRecord::Base
  extend Enumerize

  attr_accessible :description, :name, :kind
  enumerize :kind, in: [:message_syntax, :message_profanity, :message_length]

  has_many :commit_metrics, :dependent => :destroy

  validates :name, presence: true, length: { maximum: 255 }
  validates :kind, presence: true, uniqueness: { case_sensitive: false }
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :company, :name

  validates :name, presence: true, length: { maximum: 255 }

  has_many :repositories, :as => :ownerable

  def to_s
    name
  end
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  attr_accessible :name, :path, :source, :description, :clone_url, :external_id, :external_type, :is_fork

  validates :name, length: { maximum: 255 }, presence: true
  validates :path, length: { maximum: 255 }, if: -> { path.present? }
  validates :clone_url, length: { maximum: 255 }, presence: true

  has_many :commits, :dependent => :destroy

  belongs_to :ownerable, polymorphic: true
  belongs_to :user

  def to_s
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :name, :login, :image, :password, :password_confirmation, :birthday

  validates :email, uniqueness: { case_sensitive: false }
  validates :login, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, allow_blank: true
  validates :name, length: { maximum: 255 }

  has_many :auth_tokens
  has_many :authorizations
  has_many :user_badges, :dependent => :destroy
  has_many :repositories, dependent: :nullify
  has_one :committer, foreign_key: :email, primary_key: :email
  has_many :commit_metrics

  def guest?
    false
  end

  def build_auth_token
    token = SecureHelper.generate_token
    expired_at = Time.current + configus.token.lifetime
    auth_tokens.build :authentication_token => token, :expired_at => expired_at
  end

  class << self
    def birthday_year_min
      Date.today.year - 90
    end

    def birthday_year_max
      Date.today.year - 10
    end
  end
end

app/models/user/auth_token.rb
class User::AuthToken < ActiveRecord::Base

  belongs_to :user

  attr_accessible :authentication_token, :expired_at 

  validates :user, :presence => true
  validates :authentication_token, :presence => true, :uniqueness => true
  validates :expired_at, :presence => true

  def to_s
    authentication_token
  end

  def expired?
    expired_at < Time.current
  end
end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base
  attr_accessible :badge_id, :user_id

  belongs_to :user
  belongs_to :badge

  validates :user, presence: true
  validates :bage, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :sign_in_by_token

  include AuthHelper
  include SocNetworkHelper
  include FlashHelper

  helper_method :signed_in?, :current_user
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  helper_method :title, :base_title

  private

    def base_title
      t('.base_title')
    end

    def title(part = nil)
      @parts ||= [base_title]
      unless part
        return nil if @parts.blank?
        return @parts.join(' - ')
      end
      @parts << part
    end
end

app/controllers/web/hooks_controller.rb
class Web::HooksController < Web::ApplicationController
  def create
    Resque.enqueue_to :hook, ::HookWorker, params[:payload]
    head :ok
  end
end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController

  def create
    @email = params[:session][:email]
    user = ::User.find_by_email(@email)
    if user && user.authenticate(params[:session][:password])
      reset_session
      sign_in(user)
      if user.admin?
        redirect_to admin_root_path
      else
        redirect_to root_path
      end
    else
      flash_error
      redirect_to root_path
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/web/users_controller.rb
class Web::UsersController < Web::ApplicationController

  def dashboard
    authenticate!

    @commits = Commit.scoped
  end

  def profile
    @user = User.find_by_login!(params[:login]) if params[:login]
    @user ||= current_user if signed_in?
    raise ActiveRecord::RecordNotFound unless @user.present?
  end
end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def show
    redirect_to dashboard_path if signed_in?
    @commits = Commit.scoped
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include CustomUrlHelper

  def link_to_repository(repository)
    "/#{repository.user.login}/#{repository.name}/"
  end

  def link_to_commit(commit)
    repo = link_to_repository commit.repository
    "#{repo}commits/#{commit.sha}"
  end

  def link_to_user(email)
    user = User.find_by_email email

    if user
      "/profiles/#{user.login}"
    end
  end
end

app/helpers/web/hook_helper.rb
module Web::HookHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render 'layouts/web/shared/head'
  %body
    .main
      - if signed_in?
        = render :partial => 'layouts/web/shared/menu'
      %header
        .container-fluid
          .row
            .span12
              %h1
                = link_to t('commits_io'), root_path, class: 'brand'
              %p
                Show that you are the best in commiting!
      .content
        = render :partial => 'layouts/web/shared/flash', :object => flash
        = yield
      .main-footer
    .footer
      = render :partial => 'layouts/web/shared/footer'

app/views/layouts/web/shared/_flash.html.haml
- [:notice, :error, :success].each do |key|
  - if flash && flash[key].present?
    %div{ :class => "alert alert-#{key.to_s}" }
      %a.close{'data-dismiss' => 'alert'}×
      = flash[key]

app/views/layouts/web/shared/_footer.html.haml
%footer
  .container-fluid
    .row
      .span12
        %p © 2013, commits.io

app/views/layouts/web/shared/_head.html.haml
%meta{:charset => "utf-8"}/
%meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}/
%title= "commits.io"
/[if lt IE 9]

%link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:400italic,400", :rel => "stylesheet"}/
%link{:href => "http://fonts.googleapis.com/css?family=Droid+Sans", :rel => "stylesheet"}/
%link{:href => "http://fonts.googleapis.com/css?family=Lobster", :rel => "stylesheet"}/

= javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
= stylesheet_link_tag "application", :media => "all"
= javascript_include_tag "application"
= csrf_meta_tags

app/views/layouts/web/shared/_menu.html.haml
.navbar.navbar-custom
  .navbar-inner
    %ul.nav.pull-right
      %li
        =link_to t(".Profile"), profile_path
      %li
        =link_to t(".Settings"), settings_personal_path
      %li
        = link_to t('.sign_out'), session_path, method: :delete

app/views/web/shared/_commits.html.haml
.row-fluid
  .span6
    %h2= t('.Top 10 best commits')
    .commit-block
      - commits.top.each do |commit|
        .item
          .rate= number_to_percentage commit.percent, :precision => 1
          .subcontent
            %a.name{:href => link_to_commit(commit) }
              = commit.message
            .summary
              .pull-left
                %small
                  %a.repo{:href => link_to_repository(commit.repository) }
                    = commit.repository.name
                %br
                %small
                  %a.author{:href => link_to_user(commit.committer.email) } 
                    = commit.committer.name
              .pill-right.right
                %small= commit.committed_at
              .clearfix
  .span6
    %h2= t('.Top 10 worst commits')
    .commit-block.worse
      - commits.bottom.each do |commit|
        .item
          .rate= number_to_percentage commit.percent, :precision => 1
          .subcontent
            %a.name{:href => link_to_commit(commit) }
              = commit.message
            .summary
              .pull-left
                %small
                  %a.repo{:href => link_to_repository(commit.repository) }
                    = commit.repository.name
                %br
                %small
                  %a.author{:href => link_to_user(commit.committer.email) } 
                    = commit.committer.name
              .pill-right.right
                %small= commit.committed_at
              .clearfix